#!/bin/bash

set -e -u

readonly output=$1
shift

tmpdir=$(mktemp -d)
trap "rm -rf $tmpdir" EXIT

for host; do
  hostdir=$tmpdir/$host

  mkdir -p $hostdir/var/log/ganeti

  # Keep in sync with "qa-cleanup-logs" script
  rsync -av \
    root@$host:/var/log/ganeti/ $hostdir/var/log/ganeti/

  ssh root@$host 'cat /proc/drbd || :' >$hostdir/proc-drbd.txt 2>&1
  ssh root@$host 'dmsetup info || :' >$hostdir/dmsetup-info.txt 2>&1
done

tar -C $tmpdir --xz -cvf $output .

exit 0
