#!/bin/bash

set -e -u

readonly output=$1
shift

tmpdir=$(mktemp -d)
trap "rm -rf $tmpdir" EXIT

for host; do
  hostdir=$tmpdir/$host

  mkdir -p $hostdir/var/log/ganeti

  # Keep in sync with "qa-cleanup-logs" script
  rsync -av \
    root@$host:/var/log/ganeti/ $hostdir/var/log/ganeti/

  # Also collect vcluster logs, if present
  if ssh root@$host test -d /srv/ganeti/vcluster; then
      mkdir -p $hostdir/srv/ganeti/vcluster
      rsync -av \
          root@$host:/srv/ganeti/vcluster/ $hostdir/srv/ganeti/vcluster
  fi

  ssh root@$host 'cat /proc/drbd || :' >$hostdir/proc-drbd.txt 2>&1
  ssh root@$host 'dmsetup info || :' >$hostdir/dmsetup-info.txt 2>&1
done

tar -C $tmpdir --xz -cvf $output .

exit 0
