#!/bin/bash

# Copyright (C) 2013 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

umask 0022

readonly role="$1"

# slack doesn't seem to define $HOME

if [ -z "$HOME" ]; then
  export HOME=/root # yes, hardcoded
fi

case "$role" in
  buildqa.fedora*)
    yum install -q -y \
      openssh \
      openssh-clients \
      bridge-utils \
      iproute \
      ndisc6 \
      pyOpenSSL \
      pyparsing \
      python-simplejson \
      python-inotify \
      python-lxml \
      socat \
      fping \
      patch \
      python-bitarray \
      python-ipaddr \
      python-paramiko \
      python-affinity

    echo "Please make sure that the driving buildslave has passwordless" \
         "SSH access to this machine"

    systemctl restart NetworkManager.service
    ;;

  buildqa.wheezy*-kvm)
     mkdir -p /srv/ganeti/file-storage
     apt-get install -y qemu-kvm \
       fping socat \
       python-openssl \
       python-ipaddr \
       python-simplejson \
       python-inotifyx \
       python-bitarray \
       python-paramiko \
       python-pycurl \
       python-pyparsing \
       python-pyinotify \
       kpartx
     ;;

  *)
    echo "Unknown role '$1'" 1>&2
    exit 1
    ;;
esac
