#!/bin/bash

# Copyright (C) 2013 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

export DEBIAN_FRONTEND=noninteractive
umask 0022

# slack doesn't seem to define $HOME

if [ -z "$HOME" ]; then
  export HOME=/root # yes, hardcoded
fi

case "$1" in
  buildslave.wheezy*)
    apt-get update
    apt-get install -y \
      autoconf automake \
      ghc ghc-haddock \
      libghc-network-{dev,prof} \
      libghc-test-framework{,-hunit,-quickcheck2}-{dev,prof} \
      libghc-json-{dev,prof} \
      libghc-curl-{dev,prof} \
      libghc-hinotify-{dev,prof} \
      libghc-parallel-{dev,prof} \
      libghc-utf8-string-{dev,prof} \
      libghc-hslogger-{dev,prof} \
      libghc-crypto-{dev,prof} \
      libghc-regex-pcre-{dev,prof} \
      libghc-attoparsec-{dev,prof} \
      libghc-vector-{dev,prof} \
      libghc-temporary-{dev,prof} \
      libghc-snap-server-{dev,prof} \
      libghc-psqueue-{dev,prof} \
      libghc6-zlib-dev \
      libpcre3 libpcre3-dev \
      cabal-install \
      hscolour hlint pandoc \
      python-sphinx python-epydoc graphviz \
      openssl python-openssl \
      python-pyparsing python-simplejson \
      python-pyinotify python-pycurl \
      python-paramiko python-yaml \
      python-bitarray python-ipaddr \
      python-mock \
      qemu-utils \
      python-coverage pep8 \
      socat fping fakeroot \
      shelltestrunner \
      pylint

    # Update cabal, unless we have done so in the last 3 days
    if [ ! -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar -o -n "$(find $HOME/.cabal -path $HOME/.cabal/packages/hackage.haskell.org/00-index.tar -mtime +2)" ]; then
      cabal update
    fi

    cabal install --global \
        base64-bytestring \
        lens-3.10.2 \
        'lifted-base>=0.1.2'

    ;;
  buildslave.jessie*)
    apt-get update
    apt-get install -y \
      autoconf automake \
      ghc ghc-haddock \
      libghc-network-{dev,prof} \
      libghc-test-framework{,-hunit,-quickcheck2}-{dev,prof} \
      libghc-json-{dev,prof} \
      libghc-curl-{dev,prof} \
      libghc-hinotify-{dev,prof} \
      libghc-parallel-{dev,prof} \
      libghc-utf8-string-{dev,prof} \
      libghc-hslogger-{dev,prof} \
      libghc-crypto-{dev,prof} \
      libghc-regex-pcre-{dev,prof} \
      libghc-attoparsec-{dev,prof} \
      libghc-vector-{dev,prof} \
      libghc-temporary-{dev,prof} \
      libghc-base64-bytestring-{dev,prof} \
      libghc-lifted-base-{dev,prof} \
      libghc-lens-{dev,prof} \
      libghc-snap-server-{dev,prof} \
      libghc-psqueue-{dev,prof} \
      libghc-zlib-dev \
      libpcre3 libpcre3-dev \
      cabal-install \
      hscolour hlint pandoc \
      python-sphinx python-epydoc graphviz \
      openssl python-openssl \
      python-pyparsing python-simplejson \
      python-pyinotify python-pycurl \
      python-paramiko python-yaml \
      python-bitarray python-ipaddr \
      python-mock \
      qemu-utils \
      python-coverage pep8 \
      socat fping fakeroot \
      shelltestrunner \
      pylint

    ;;
  buildslave.ubuntu1304*)
    apt-get update
    apt-get install -y \
      autoconf automake \
      ghc ghc-haddock \
      libghc-network-{dev,prof} \
      libghc-test-framework{,-hunit,-quickcheck2}-{dev,prof} \
      libghc-json-{dev,prof} \
      libghc-curl-{dev,prof} \
      libghc-hinotify-{dev,prof} \
      libghc-parallel-{dev,prof} \
      libghc-utf8-string-{dev,prof} \
      libghc-hslogger-{dev,prof} \
      libghc-crypto-{dev,prof} \
      libghc-regex-pcre-{dev,prof} \
      libghc-attoparsec-{dev,prof} \
      libghc-vector-{dev,prof} \
      libghc-temporary-{dev,prof} \
      libghc-lens-{dev,prof} \
      libghc-lifted-base-{dev,prof} \
      libghc-snap-server-{dev,prof} \
      libghc-psqueue-{dev,prof} \
      libpcre3 libpcre3-dev \
      libghc-zlib-dev libghc-base64-bytestring-dev \
      hscolour hlint pandoc \
      python-sphinx python-epydoc graphviz \
      openssl python-openssl \
      python-pyparsing python-simplejson \
      python-pyinotify python-pycurl \
      python-paramiko python-yaml \
      python-bitarray python-ipaddr \
      python-mock \
      qemu-utils \
      python-coverage pep8 \
      socat fping fakeroot \
      shelltestrunner

    apt-get install -qq -y python-dev build-essential

    easy_install \
      sphinx==1.1.3 \
      logilab-common==0.57.1 \
      logilab-astng==0.23.0 \
      pylint==0.25.0 \
      pep8==1.2
    ;;
  buildslave.fedora*)
    yum install -q -y \
    autoconf automake \
    cabal-install cabal-dev \
    fakeroot \
    ghc \
    ghc-json ghc-json-devel \
    ghc-network ghc-network-devel \
    ghc-parallel ghc-parallel-devel \
    ghc-utf8-string ghc-utf8-string-devel \
    ghc-regex-pcre-devel ghc-hinotify-devel \
    ghc-vector-devel \
    graphviz \
    hlint \
    libcurl libcurl-devel \
    pandoc \
    pyOpenSSL \
    pyparsing \
    python-bitarray \
    python-inotify \
    python-mock \
    python-ipaddr \
    python-sphinx \
    python-yaml \
    python-lxml \
    python-paramiko \
    python-simplejson \
    patch \
    zlib-devel \
    qemu-img \
    socat

    # Update cabal, unless we have done so in the last 3 days
    if [ ! -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar -o -n "$(find $HOME/.cabal -path $HOME/.cabal/packages/hackage.haskell.org/00-index.tar -mtime +2)" ]; then
      cabal update
    fi

    cabal install --global \
      attoparsec \
      crypto \
      curl==1.3.7 \
      hscolour==1.20.3 \
      hslogger==1.1.4 \
      snap-server==0.8.1 \
      PSQueue==1.1 \
      quickcheck==2.5.1.1 \
      shelltestrunner==1.3.1

    cabal install --global \
      temporary==1.1.2.3 \
      test-framework-quickcheck2

    cabal install --global \
        base64-bytestring zlib \
        lens-3.10.2 \
        lifted-base==0.2.1.1
    ;;
  *)
    echo "Unknown role '$1'" 1>&2
    exit 1
    ;;
esac
