#!/bin/sh

# Copyright (C) 2013 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

export DEBIAN_FRONTEND=noninteractive
umask 0022

apt-get install -qq -y vim make git bash-completion

apt-get install -qq -y python-twisted

apt-get install -qq -y python-setuptools

case "$1" in
  buildslave.squeeze*)
    easy_install buildbot-slave==0.8.6p1

    if ! getent passwd buildbot >/dev/null; then
      adduser --system --group --disabled-password \
        --home /srv/buildbot --shell /bin/bash \
        buildbot
    fi
    ;;
  buildslave.wheezy*)
    apt-get install -qq -y buildbot-slave
    ;;
  *)
    echo "Unknown role '$1'" 1>&2
    exit 1
    ;;
esac
